# Generated by Django 4.2.7 on 2024-10-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='usere',
            new_name='user',
        ),
    ]
